server:
  port: 8081
spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  profiles:
    active:
  datasource:
    url: jdbc:mysql://localhost:3306/storage?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
mybatis:
  typeAliasesPackage: com.example.storage
  mapperLocations: classpath*:mapping/*.xml